--!strict

export type EnumType = string

local PlayerDataKey = {
	__receiptHistory = "__receiptHistory" :: "__receiptHistory",
	Currency = "Currency" :: "Currency",
	Info = "Info" :: "Info",
	Codes = "Codes" :: "Codes",
	Setting = "Setting" :: "Setting",
	Date = "Date" :: "Date",
	Store = "Store" :: "Store",
	Items = "Items" :: "Items",
	Statistic = "Statistic" :: "Statistic",
	AFK = "AFK" :: "AFK",
	Tags = "Tags" :: "Tags",
	LimitedStore = "LimitedStore" :: "LimitedStore",
	Battlepass = "Battlepass" :: "Battlepass",
	Invite = "Invite" :: "Invite",
	Vote = "Vote" :: "Vote",
	Zone = "Zone" :: "Zone",
	Potion = "Potion" :: "Potion",
	Tutorial = "Tutorial" :: "Tutorial",
	SeasonPass = "SeasonPass" :: "SeasonPass",
	BadgeClaimed = "BadgeClaimed" :: "BadgeClaimed",
	LeaderboardClaim = "LeaderboardClaim" :: "LeaderboardClaim",
	Titles = "Titles" :: "Titles",
	AxeTycoon = "AxeTycoon" :: "AxeTycoon",
}

return PlayerDataKey
