--!strict

export type EnumType = string

local ProductKeys = {
	cash1 = "cash1" :: "cash1",
	cash2 = "cash2" :: "cash2",
	cash3 = "cash3" :: "cash3",
	cash4 = "cash4" :: "cash4",
	cash5 = "cash5" :: "cash5",
	cash6 = "cash6" :: "cash6",
	vip = "vip" :: "vip",
	doubleExp = "doubleExp" :: "doubleExp",
	serverLuck = "serverLuck" :: "serverLuck",
	spin1 = "spin1" :: "spin1",
	spin10 = "spin10" :: "spin10",
}

return ProductKeys
