--!strict

export type EnumType = string

local RemoteKey = {
	Group = "Group" :: "Group",
	Sign = "Sign" :: "Sign",
	Code = "Code" :: "Code",
	NotifyEvent = "NotifyEvent" :: "NotifyEvent",
	Exchange = "Exchange" :: "Exchange",
	Verify = "Verify" :: "Verify",
	Online = "Online" :: "Online",
	Buy = "Buy" :: "Buy",
	Upgrade = "Upgrade" :: "Upgrade",
	Robux = "Robux" :: "Robux",
	Min15 = "Min15" :: "Min15",
	Min30 = "Min30" :: "Min30",
	Use = "Use" :: "Use",
	Leaderboard = "Leaderboard" :: "Leaderboard",
}

return RemoteKey
