--!strict

--[[
	A place to put named keybinds for consistent controls across the game
--]]

local Keybind = {
	GamepadPrimaryAction = Enum.KeyCode.ButtonA,
	GamepadBackAction = Enum.KeyCode.ButtonB,
	KeyboardPrimaryAction1 = Enum.KeyCode.Return,
	KeyboardPrimaryAction2 = Enum.KeyCode.KeypadEnter,
	KeyboardBackAction = Enum.KeyCode.Backspace,
	
	GamepadInventoryOpenButton = Enum.KeyCode.ButtonY,
	KeyboardInventoryOpenButton = Enum.KeyCode.Backquote,



	KeyboardResetDataButton = Enum.KeyCode.RightBracket,
	
	GamepadButtonY = Enum.KeyCode.ButtonY,
	GamepadButtonB = Enum.KeyCode.ButtonB,
	GamepadButtonX = Enum.KeyCode.ButtonX,
	GamepadButtonA = Enum.KeyCode.ButtonA,
	
	GamepadButtonDPadUp = Enum.KeyCode.DPadUp,
	GamepadButtonDPadDown = Enum.KeyCode.DPadDown,
	GamepadButtonDPadRight = Enum.KeyCode.DPadRight,
	GamepadButtonDPadLeft = Enum.KeyCode.DPadLeft,
	
	KeyboardTab = Enum.KeyCode.Tab,
	
	keyboardNumber1 = Enum.KeyCode.One,
	keyboardNumber2 = Enum.KeyCode.Two,
	keyboardNumber3 = Enum.KeyCode.Three,
	keyboardNumber4 = Enum.KeyCode.Four,
	keyboardNumber5 = Enum.KeyCode.Five,
	keyboardNumber6 = Enum.KeyCode.Six,
	
	keyboardNumbers = {
		Enum.KeyCode.One,
		Enum.KeyCode.Two,
		Enum.KeyCode.Three,
		Enum.KeyCode.Four,
		Enum.KeyCode.Five,
		Enum.KeyCode.Six,
	},
	
	
	Space = Enum.KeyCode.Space,
	
	A = Enum.KeyCode.A,
	D = Enum.KeyCode.D,
	
	ReleaseButton = Enum.KeyCode.ButtonX,
	
	
}

return Keybind
