export type EnumType = string

local AxeCategory = {
	Axe_1 = "1",
	Axe_2 = "2",
	Axe_3 = "3",
	Axe_4 = "4",
	Axe_5 = "5",
	Axe_6 = "6",
	Axe_7 = "7",
	Axe_8 = "8",
	Axe_9 = "9",
	Axe_10 = "10",
	Axe_11 = "11",
	Axe_12 = "12",
	Axe_13 = "13",
	Axe_14 = "14",
	Axe_15 = "15",
	Axe_16 = "16",
	Axe_17 = "17",
	Axe_18 = "18",
	Axe_19 = "19",
	Axe_20 = "20",
	Axe_21 = "21",
	Axe_22 = "22",
	Axe_23 = "23",
	Axe_24 = "24",
}

return AxeCategory
