--!strict

export type EnumType = string

local ItemKeyCategory = {
	cash = "cash" :: "cash",
	luck1 = "luck1" :: "luck1",
	luck2 = "luck2" :: "luck2",
	moveSpeed = "moveSpeed" :: "moveSpeed",
	autoCollect = "autoCollect" :: "autoCollect",
	serverLuck = "serverLuck" :: "serverLuck",
	enchant1 = "enchant1" :: "enchant1",
	enchant2 = "enchant2" :: "enchant2",
	SpinTicket = "SpinTicket" :: "SpinTicket",
}

return ItemKeyCategory
