export type EnumType = string

local WoodCategory = {
	Wood_1 = "1",
	Wood_2 = "2",
	Wood_3 = "3",
	Wood_4 = "4",
	Wood_5 = "5",
	Wood_6 = "6",
	Wood_7 = "7",
	Wood_8 = "8",
	Wood_9 = "9",	
	Wood_10 = "10",
	Wood_11 = "11",
	Wood_12 = "12",
	Wood_13 = "13",
	Wood_14 = "14",
	Wood_15 = "15",
	Wood_16 = "16",
	Wood_17 = "17",
	Wood_18 = "18",
	Wood_19 = "19",
	Wood_20 = "20",
	Wood_21 = "21",
	Wood_22 = "22",
	Wood_23 = "23",
	Wood_24 = "24",
}

return WoodCategory
